
---
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  build:
    commands:
      - >
        docker build -t arronmoore_com .
      - docker tag arronmoore_com $REPO_URI:build-arronmoore_com

  post_build:
    commands:
      - docker push $REPO_URI:build-arronmoore_com