
---
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  build:
    commands:
      - >
        docker build
        -t arronmoore_com .
  post_build:
    commands:
      - docker push $REPO_URI:arronmoore_com